version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3010:3000"
    environment:
      - PORT=3000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    depends_on:
      - database
    networks:
      - vitalsync-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - vitalsync-network

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - vitalsync-network

networks:
  vitalsync-network:
    driver: bridge

volumes:
  pgdata:
